export const phoneRegExp = /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/
export const idenRegExp = /[1-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]/
export const term  : string = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ullamcorper velit sed ullamcorper morbi. Bibendum neque egestas congue quisque egestas diam in. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam purus. Tellus in hac habitasse platea dictumst vestibulum rhoncus est pellentesque. In nulla posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Sociis natoque penatibus et magnis. Dignissim enim sit amet venenatis urna. Amet justo donec enim diam vulputate ut pharetra sit. Gravida quis blandit turpis cursus in hac habitasse platea. Venenatis tellus in metus vulputate eu. Ornare suspendisse sed nisi lacus. Nunc sed blandit libero volutpat sed. Odio tempor orci dapibus ultrices in iaculis. Bibendum enim facilisis gravida neque convallis a cras semper. Quam pellentesque nec nam aliquam sem et.

Varius vel pharetra vel turpis nunc eget. Diam maecenas ultricies mi eget mauris pharetra. Sed nisi lacus sed viverra. Urna duis convallis convallis tellus id interdum. Quam vulputate dignissim suspendisse in est ante in nibh. Vel facilisis volutpat est velit egestas dui. Dictumst vestibulum rhoncus est pellentesque elit. In hac habitasse platea dictumst quisque sagittis purus sit. Bibendum ut tristique et egestas quis ipsum suspendisse. In hendrerit gravida rutrum quisque non tellus orci ac. Elit duis tristique sollicitudin nibh sit.

Dui nunc mattis enim ut tellus elementum. Ornare massa eget egestas purus viverra accumsan in. Senectus et netus et malesuada fames. Ornare arcu dui vivamus arcu. Volutpat sed cras ornare arcu dui vivamus arcu. Egestas quis ipsum suspendisse ultrices gravida dictum. Amet nisl suscipit adipiscing bibendum est. Tellus orci ac auctor augue mauris augue neque gravida in. Morbi tempus iaculis urna id volutpat lacus. Maecenas volutpat blandit aliquam etiam erat velit scelerisque in dictum. Tellus id interdum velit laoreet id donec ultrices tincidunt arcu. Massa massa ultricies mi quis hendrerit dolor magna. Etiam sit amet nisl purus in mollis nunc. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Sed adipiscing diam donec adipiscing tristique risus.

Sed tempus urna et pharetra pharetra massa massa ultricies. Vitae congue eu consequat ac felis donec et odio pellentesque. Amet nisl suscipit adipiscing bibendum est ultricies integer quis auctor. Mauris commodo quis imperdiet massa tincidunt. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Auctor urna nunc id cursus metus aliquam eleifend mi. Bibendum at varius vel pharetra vel turpis nunc. Urna nec tincidunt praesent semper feugiat. Consectetur lorem donec massa sapien faucibus et molestie. Sed felis eget velit aliquet sagittis id consectetur purus ut. Gravida dictum fusce ut placerat orci.

Eu facilisis sed odio morbi quis. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor. Orci a scelerisque purus semper eget duis at tellus at. Tincidunt tortor aliquam nulla facilisi cras. Consectetur purus ut faucibus pulvinar elementum integer. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Pharetra vel turpis nunc eget lorem dolor. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa. Ullamcorper morbi tincidunt ornare massa eget egestas. Ac turpis egestas sed tempus. Consectetur adipiscing elit ut aliquam purus sit. Viverra nibh cras pulvinar mattis nunc sed blandit. Nunc sed id semper risus in hendrerit gravida. Id interdum velit laoreet id donec ultrices. Accumsan lacus vel facilisis volutpat est velit egestas. Nisi scelerisque eu ultrices vitae auctor. Non sodales neque sodales ut etiam sit. Commodo ullamcorper a lacus vestibulum sed arcu.

Facilisis sed odio morbi quis commodo. Nullam ac tortor vitae purus faucibus ornare suspendisse sed nisi. Risus feugiat in ante metus. Sit amet nisl purus in mollis. Suscipit adipiscing bibendum est ultricies integer quis. Aliquet risus feugiat in ante metus dictum at. Augue lacus viverra vitae congue eu. Viverra aliquet eget sit amet tellus cras. Ornare arcu dui vivamus arcu felis. Arcu ac tortor dignissim convallis aenean et tortor at. Imperdiet dui accumsan sit amet nulla. Fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate. Sagittis orci a scelerisque purus semper eget duis. Morbi blandit cursus risus at.

Dictum at tempor commodo ullamcorper a. Pellentesque habitant morbi tristique senectus. Enim praesent elementum facilisis leo vel fringilla est. Sagittis aliquam malesuada bibendum arcu vitae. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Sed elementum tempus egestas sed sed risus pretium. Nisl purus in mollis nunc sed id. Lobortis scelerisque fermentum dui faucibus in ornare quam. Tellus elementum sagittis vitae et. Ultricies leo integer malesuada nunc vel risus. Vel eros donec ac odio tempor. Tortor at auctor urna nunc id cursus. Turpis egestas sed tempus urna. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Lectus arcu bibendum at varius vel pharetra vel turpis. Fermentum iaculis eu non diam phasellus vestibulum lorem.

Risus sed vulputate odio ut enim. Sem integer vitae justo eget magna. Nec dui nunc mattis enim ut tellus elementum sagittis. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Mollis nunc sed id semper risus. Ornare suspendisse sed nisi lacus sed viverra tellus in. Condimentum lacinia quis vel eros. Vitae sapien pellentesque habitant morbi tristique. Mi proin sed libero enim sed faucibus turpis in eu. Eget velit aliquet sagittis id consectetur purus ut faucibus. Quis risus sed vulputate odio ut enim blandit. Feugiat sed lectus vestibulum mattis ullamcorper velit sed. Tincidunt lobortis feugiat vivamus at.

Sit amet dictum sit amet justo donec. Etiam sit amet nisl purus in. Aliquam sem fringilla ut morbi tincidunt augue interdum velit euismod. Sit amet mauris commodo quis imperdiet massa tincidunt. Adipiscing at in tellus integer feugiat scelerisque varius morbi. Pellentesque elit ullamcorper dignissim cras tincidunt. Pharetra et ultrices neque ornare aenean euismod elementum. Facilisis gravida neque convallis a cras semper. Nunc consequat interdum varius sit amet mattis. In ornare quam viverra orci sagittis eu volutpat odio facilisis. Blandit aliquam etiam erat velit scelerisque. Habitant morbi tristique senectus et netus et malesuada.

A erat nam at lectus urna duis convallis convallis tellus. Justo donec enim diam vulputate ut pharetra sit amet. Habitant morbi tristique senectus et netus et malesuada fames ac. Euismod lacinia at quis risus sed. Fusce ut placerat orci nulla pellentesque. Sem integer vitae justo eget. Odio aenean sed adipiscing diam donec. Ullamcorper dignissim cras tincidunt lobortis. Habitant morbi tristique senectus et netus et malesuada. In fermentum et sollicitudin ac orci. Neque vitae tempus quam pellentesque nec nam aliquam sem. Vel facilisis volutpat est velit egestas dui id ornare arcu. Vitae congue eu consequat ac felis donec et odio. Fusce id velit ut tortor pretium viverra suspendisse.`
